name: Build Validation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
