name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Rewrite titles
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: rewrite-title

      - name: Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepress/dist
