name: Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pull changes
        run: |
          git remote add vite https://github.com/vitejs/vite
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Fetch and Checkout datas
        run: |
          git fetch vite
          git fetch origin
          git checkout --track origin/sync

      - name: Diff
        run: |
          git diff sync vite/main -- docs >> sync
          git log sync..vite/main -- docs >> sync

      - name: Merge from vite
        run: |
          git pull vite main
          git push origin sync
          git checkout main

      - name: Forced merge from vite
        if: ${{ failure() }}
        run: |
          git pull vite main
          git push origin +sync
          git checkout main

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Run sync script
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: sync ${{ github.token }}
